### ISSUE TITLE
Can't create projects under an org

### ISSUE THREAD

**Issue by evanplaice** [webcomponents-dev/webcomponents.dev#16]
**Describe the bug**

When I hit the `+` under an org the project is created under my personal user account listing

**To Reproduce**
1. Go to the vanillawc org
2. Click on the `+` button to add a new project
3. Go to the org, the project isn't there
4. Go to my personal account, it is there

**Expected behavior**
I'd expect the new project to be listed under the org after creation

**Device**
 - OS: ElementaryOS (Ubuntu based)
 - Browser: Chromium
 - Version: 79.0.3945.117 (Official Build)

**Additional context**
This isn't really a high-priority issue as the project can be reassigned to the org after creation.

**Comment by georges-gomes** [comment]
Hi Evan! Just so that yesterday as well 🤦‍♂️
Thanks for reporting 👍

It's because of the new template selection.
Will be fixed in the next couple of days!

Sorry for the inconvenience.
Cheers

**Comment by evanplaice** [comment]
No worries, it was hardly an inconvenience. BTW, great job. Vanilla web component support is working beautifully.

I manged to migrate all but 2 of the VanillaWC collection.

WC-Monaco-Editor - which isn't surprising since it relies heavily on globals and WCD uses Monaco as well.

WS-Social-Link - External SVGs are blocked by CORS. I still have to verify but I'm pretty sure jsDelivr is the cause.

**Comment by georges-gomes** [comment]
Hi Evan,
Fixed now 👍

**Comment by georges-gomes** [comment]
WC-Monaco-Editor : The components run in an Iframe so it should work... If you have time to recreate the projet I can have a look 👍

WS-Social-Link : We will do something about assets. CORS is not easy. If you think we can do something let us know.

**Comment by evanplaice** [comment]
Here's are the links.

- [wc-monaco-editor-demo](https://webcomponents.dev/edit/l2Ut0nwlkg4ydUEIpmoW)
- [wc-social-link-demo](https://webcomponents.dev/edit/urflGeFYnQ2S66ff46yE)

Surprisingly, Monaco Editor is working now despite throwing errors.

This Monaco setup in this demo uses language-server-protocol service workers for code analysis. The error may just be due to the service workers failing to load and the editor falling back to processing everything on the main thread.

**Comment by georges-gomes** [comment]
There is nothing we can for wc-mona-editor-demo I think.

Regarding, wc-social-link-demo, it's related to

![image](https://user-images.githubusercontent.com/5250572/73338198-5a7df600-4276-11ea-9493-d3780af522b9.png)

from

![image](https://user-images.githubusercontent.com/5250572/73338255-75e90100-4276-11ea-99e2-3f7c6ded9c79.png)

Because of the security constraints he doesn't want to get this data from jsdelivr.

I actually have the same problem with the demo page
https://vanillawc.github.io/wc-social-link/demo/link-attribute.html

You should try getting the pathname from the `import.meta.url` directly without going through the `new URL()`

Cheers
