### ISSUE TITLE
Cannot find module '${foo}' or its corresponding type declarations.(2307)

### ISSUE THREAD

**Issue by bennypowers** [webcomponents-dev/webcomponents.dev#39]
**Describe the bug**
With certain modules, I'm unable to load types in the editor.

Examples:
> Cannot find module '@apollo-elements/mixins/apollo-query-mixin' or its corresponding type declarations.(2307)

> Cannot find module 'lit-element' or its corresponding type declarations.(2307)

**To Reproduce**
1. Go to https://webcomponents.dev/edit/di6jOwGTWj7uFEWJK741?file=src%2FHello.ts
2. Observe error 

1. Go to https://webcomponents.dev/edit/PmmwJU9LjBDHlkO8WiSq?file=src%2FHello.ts
2. Observe error

**Expected behavior**
No type errors in packages with types

**Screenshots**

<img width="602" alt="Screen Shot 2021-01-10 at 14 31 26" src="https://user-images.githubusercontent.com/1466420/104122910-8f347180-5350-11eb-93df-3489eeeed719.png">

**Comment by gqio** [comment]
Hi @bennypowers 

Many thanks for reporting those issues

Regarding the first bug but it was due to our import parser not supporting yet the private Properties/Methods
Lib have been upgraded to match the use case 
![image](https://user-images.githubusercontent.com/1063530/104190987-3252bd00-541d-11eb-8b41-0658b83049dc.png)

Regarding the second bug it was due to our typings provider not using the same typescript version as the front end app. Typescript have been updated on our typings provider and released

![image](https://user-images.githubusercontent.com/1063530/104191193-7b0a7600-541d-11eb-8156-77798f1fb1a7.png)

For the later you may need to delete the front application cache of `packd` if you encounter any remaining issue
![image](https://user-images.githubusercontent.com/1063530/104191255-92496380-541d-11eb-899a-ebb232093e07.png)

Release in progress

Thanks.
