### ISSUE TITLE
git-push error

### ISSUE THREAD

**Issue by Geoffrey-Pliez** [webcomponents-dev/webcomponents.dev#44]
**Describe the bug**
impossible to push my code on github.

**To Reproduce**
1. Click on push 
2. See error on console

service.ts:190 POST https://us-central1-prd-webcomponents-editor.cloudfunctions.net/git-push 500

**Expected behavior**
push my code on github

**Screenshots**
![image](https://user-images.githubusercontent.com/4426520/104940981-c939ef00-59b2-11eb-8f7a-823d9de2c91c.png)

**Device**
 - OS: Windows
 - Browser: Chrome
 - Version: Version 90.0.4392.0 (Build officiel) canary (64 bits)

**Comment by gqio** [comment]
Hi @Geoffrey-Pliez 

I'm looking at it.

Keep you posted.

Thanks

**Comment by gqio** [comment]
Ok I found the issue @Geoffrey-Pliez :D it was a tricky one

Apparently you don't have a display name in Github in your account.
We use this information to add git information while pushing to GitHub (aka git config user.name="$displayName")

And GitHub refuse to push via git without those information. It's not required to match your display name but for the git history it's better to keep consistency between your display name and the user.name in the commit history.

The fastest way to solve the issue is to provide a display name with your GitHub account, but maybe you don't to.
In the mean time I will push a fix to default this name (we didn't experienced yet this issue, lucky us :) )

Thanks for reporting this issue.
I'll keep you posted when the issue will be fixed and delivered.

Best

**Comment by gqio** [comment]
You can configure it here : 
![image](https://user-images.githubusercontent.com/1063530/105041758-ae738300-5a63-11eb-8855-fbbc96894ed8.png)

**Comment by gqio** [comment]
Hi @Geoffrey-Pliez ,

Should be fixed and delivered by now.
Could you please confirm it worked for you ?

Thanks.

**Comment by Geoffrey-Pliez** [comment]
Hi @gqio 

Thank you for your answer.

For me, the issue is solved.

Thanks again
